name: test
on: [push]

defaults:
  run:
    shell: bash
jobs:
  build-and-test-release:
    name: build-and-test-release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cargo build
        run:  cargo build

      - name: cargo test 
        run:  RUST_LOG=trace cargo test -- --test-threads 1 --color always

